name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Download SDL2
      run: sudo apt install libsdl2-2.0-0 libsdl2-dev
    
    - name: Install go dependencies
      run: go install

    - name: Test
      run: go test -short ./... -v
